# Easy Admin
easy_admin:
    site_name: 'PELEJA <em style="font-size: 50%;">PHP com Rapadura.</em>'
    entities:
        User:
          class: PhpComRapadura\UserBundle\Entity\User
        Community:
            class: PhpComRapadura\CommunityBundle\Entity\Community
            list:
                fields:
                    - id
                    - name
                    - { property: 'avatar', type: 'image', base_path: /uploads/images/communities }
            show:
                fields:
                    - id
                    - name
                    - { property: 'avatar', type: 'image', base_path: /uploads/images/communities }
            form:
                fields:
                    - name
                    - { property: 'description', type: 'ckeditor', type_options: { required: false } }
                    - { property: 'avatarFile', type: 'vich_image', type_options: { required: false } }